### ISSUE TITLE
Handle large websocket messages spread out across 2+ messages

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#97] opened 2016-02-16 16:10 UTC
If a websocket message is large enough, the data will be sent across 2 or more separate messages. We don't currently handle that in the rewriting code (either with our custom WS code or the library).

We're only rewriting messages in the client -> kernel gateway direction. `execute_request` messages coming from the client should be small, since the `code` section will just be an index. Therefore, there are 2 scenarios (at least) that we need to worry about:

1. When replacing the the index with actual code, that increase the size of the message. Of course, the max size for a message is around 1MB (I think), so the chances of there being a code block larger than that are pretty small. But it is still a possibility.
2. Ensure that any other messages are properly passed through without modification. That way, if there is data that is too large and is spread across multiple messages, the server should just pass it through.

**Comment by parente** [comment] 2016-03-27 02:37
Possible that #156 is related to this? Maybe the widget data messages are large when there are a lot of registrations in the streaming demo?

**Comment by jhpedemonte** [comment] 2016-03-28 15:13
Server will output the error `insufficient data for frame` if this is the case (when logging is turned on). Have you seen this in #156?

**Comment by parente** [comment] 2016-03-28 15:29
Haven't tried to reproduce with logging on.

**Comment by parente** [comment] 2016-04-12 14:20
With logging on, yes, I see the insufficient message. The logs are in #156.

**Comment by parente** [comment] 2016-04-12 14:23
> We're only rewriting messages in the client -> kernel gateway direction. execute_request messages coming from the client should be small, since the code section will just be an index. 

This is true, but it assumes we're not touch messages from kernel gateway to client. But the log messages show we definitely are still building WebSocketFrame object for messages flowing from KG -> client, even though we don't even modify them because they're not execute_requests. This is proven by the presence of `PROXY: received message from client WS` in the log with comm channel payloads that are responses from the kernel.

We need to be smarter about which messages we touch in `socket.emit` which appears to get invoked with data flowing in **either** direction.

**Comment by parente** [comment] 2016-04-12 14:58
Another, probably related problem, is that the bufferList object and others are globals in the api.js module. What happens when two websockets are connected and data needs to be retained in the bufferList across data events?

**Comment by parente** [comment] 2016-04-12 15:47
Few facts to note:

1. The `socket.emit` for `eventName=data` fires for both client to kernel and kernel to client messages.
2. The WebSocketFrame object mutates the BufferList instance. Both the WSF and BufferList instances are retained across calls to `processReceivedData` (https://github.com/theturtle32/WebSocket-Node/blob/19108bbfd7d94a5cd02dbff3495eafee9e901ca4/lib/WebSocketConnection.js#L272) when there is data leftover in the buffer after parsing the frame.
3. The bufferList is currently a module global, but can't be if we want to support multiple connections properly.

@jhpedemonte and I discussed the following approach:

1. Try to reuse the public interface of WebSocketConnection to deal with the framing, but ignore its socket / connection capabilities. This will beat rolling our own implementation of `processReceivedData` from scratch.
2. If we can't reuse, mimic `processReceivedData`.

**Comment by parente** [comment] 2016-04-20 12:07
Closed by #181

**Closed by parente** 2016-04-20 12:07 UTC
Labels: plumbing
